-- noinspection SqlNoDataSourceInspectionForFile
# DC SCHEMA

# --- !Ups

CREATE TABLE SEASON (
  ID   INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  YEAR INT NOT NULL UNIQUE
);

CREATE TABLE CONFERENCE (
  ID                INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  KEY               VARCHAR(127) NOT NULL UNIQUE,
  NAME              VARCHAR(127) NOT NULL UNIQUE,
  LOGO_LG_URL       VARCHAR(255) NULL,
  LOGO_SM_URL       VARCHAR(255) NULL,
  OFFICIAL_URL      VARCHAR(255) NULL,
  OFFICIAL_TWITTER  VARCHAR(255) NULL,
  OFFICIAL_FACEBOOK VARCHAR(255) NULL
);

CREATE TABLE TEAM (
  ID                INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  KEY               VARCHAR(127) NOT NULL UNIQUE,
  NAME              VARCHAR(127) NOT NULL UNIQUE,
  LONG_NAME         VARCHAR(255) NOT NULL,
  NICKNAME          VARCHAR(127) NOT NULL,
  LOGO_LG_URL       VARCHAR(255) NULL,
  LOGO_SM_URL       VARCHAR(255) NULL,
  PRIMARY_COLOR     VARCHAR(255) NULL,
  SECONDARY_COLOR   VARCHAR(255) NULL,
  OFFICIAL_URL      VARCHAR(255) NULL,
  OFFICIAL_TWITTER  VARCHAR(255) NULL,
  OFFICIAL_FACEBOOK VARCHAR(255) NULL
);


CREATE TABLE ALIAS (
  ID      INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TEAM_ID INT          NOT NULL,
  ALIAS   VARCHAR(127) NOT NULL UNIQUE
);


CREATE TABLE CONFERENCE_MAP (
  ID            INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SEASON_ID     INT NOT NULL,
  CONFERENCE_ID INT NOT NULL,
  TEAM_ID       INT NOT NULL
);

CREATE TABLE GAME (
  ID             INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SEASON_ID      INT          NOT NULL,
  HOME_TEAM_ID   INT          NOT NULL,
  AWAY_TEAM_ID   INT          NOT NULL,
  DATE           DATETIME     NOT NULL,
  LOCATION       VARCHAR(255) NULL,
  TOURNEY_KEY    VARCHAR(127) NULL,
  HOME_TEAM_SEED INT          NULL,
  AWAY_TEAM_SEED INT          NULL,
  FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAM (ID),
  FOREIGN KEY (AWAY_TEAM_ID) REFERENCES TEAM (ID)
);


CREATE TABLE RESULT (
  ID         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GAME_ID    INT NOT NULL,
  HOME_SCORE INT NOT NULL,
  AWAY_SCORE INT NOT NULL,
  PERIODS    INT NOT NULL,
  FOREIGN KEY (GAME_ID) REFERENCES GAME (ID)
);

CREATE TABLE PROJECT (
  ID   INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);


CREATE TABLE TASK (
  ID      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COLOR   VARCHAR(255) NOT NULL,
  STATUS  VARCHAR(255) NOT NULL,
  PROJECT INTEGER      NOT NULL,
  FOREIGN KEY (PROJECT) REFERENCES PROJECT (ID)
);


# --- !Downs

DROP TABLE SEASON;
DROP TABLE CONFERENCE;
DROP TABLE TEAM;
DROP TABLE ALIAS;
DROP TABLE CONFERENCE_MAP;
DROP TABLE GAME;
DROP TABLE RESULT;
DROP TABLE TASK;
DROP TABLE PROJECT;
